fs_user_admin_groups:
    resource: "@FSUserBundle/Resources/config/routing/group.yml"
    prefix:   /admin/groups

fs_user_admin_users:
    resource: "@FSUserBundle/Resources/config/routing/user.yml"
    prefix:   /admin/users

fs_user_homepage:
    path:     /
    defaults: { _controller: FSUserBundle:Default:index }
